### ISSUE TITLE
Mining script for Atitd 10

### ISSUE THREAD

**Issue by AlaricRa** [DashingStrike/Automato-ATITD10#121]
Mining Ore and Mining Gem Scripts will not find main chat

**Comment by atitdRhaom** [comment]
The scripts for mining ore and mining gems have not been ported across to T10 yet, so the ones you are using are written for T9 in which case, no they wont :).

I will look at this later today.

**Comment by AlaricRa** [comment]
Tyvm

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by atitdRhaom** [comment]
Scripts ported to 10
