### ISSUE TITLE
fishing

### ISSUE THREAD

**Issue by Rauul666** [DashingStrike/Automato-ATITD10#423]
fishing macro broken.. Last LUA ERROR 337: bad arguement #1 to find (string expected, got nil)

**Comment by Rauul666** [comment]
it is when it changes lures

**Comment by atitdRhaom** [comment]
There are a number of things that could cause this, but I would take a guess that it is most likely that something on the clock is not readable.

**Comment by Rauul666** [comment]
![fishing](https://user-images.githubusercontent.com/94843989/142975957-31b428d6-226a-4384-9f36-a1ee37bbf0e1.jpg)

**Comment by atitdRhaom** [comment]
I'm not entirely sure why this is the case... but in that screenshot, the clock is not readable at all, which is why the fishing macro is failing to execute.

Have you done something funky with your UI size or Transparencies?
