### ISSUE TITLE
Beta flax macro now closes seed window so it can't find seeds.

### ISSUE THREAD

**Issue by Rhythmslc** [DashingStrike/Automato-ATITD10#55]
if I have it pinned for a bit before starting it will only plan a seed if I pin it right as I start it only does one grid

**Comment by atitdRhaom** [comment]
If you pin what right before you start?

**Comment by Rhythmslc** [comment]
on the one run I may have messed up but it's still unpinning the seed after the first harvest preventing multiple runs

**Comment by atitdRhaom** [comment]
Resolved
