### ISSUE TITLE
Gather.lua - new route creation broken after last update

### ISSUE THREAD

**Issue by Gluegungeek** [DashingStrike/Automato-ATITD10#90]
it is not registering the coords correctly when creating a new gather route.
the coords seem to be missing a digit. 

![image](https://user-images.githubusercontent.com/85464983/120945388-b881df80-c6ed-11eb-8eb6-27044fb6de7e.png)

**Comment by KavadATITD** [comment]
Hey @Gluegungeek we released some significant changes to OCR (how Automato reads text) today to get it working for main chat and the new windows. Unfortunately I also had to re-train it how to read coordinates with these changes, and there are a few more edge cases that are giving it trouble. You can see the coords it is reading in real time with test_find_coords: If you could provide screenshots that include the full clock where it is reading the coordinates incorrectly I can train it to handle those. Thanks!

**Comment by Gluegungeek** [comment]
2nd bug i've found. When I manually update the coords, the macro bounces back and forth between the first two coords.

**Comment by Gluegungeek** [comment]
@KavadATITD from my above screenshot. the coords should read:
648, -170
647, -168
648, -168
647, -164
etc...
in the first two entries, it did not input the 2nd and 3rd digit on the X coord
in the rest of the entries, it missed the middle digit on the X coords

**Comment by KavadATITD** [comment]
@Gluegungeek if you can provide a screenshot of the clock at those coordinates I can train it to read them properly. I'm guessing you are in a Hyksos controlled region with the yellow background. Otherwise you'll have to wait until I make a trip down to Hyksos or someone else submits a screenshot I can train on.

**Comment by Gluegungeek** [comment]
Yep it is Hyksos. I'm on the border of Swenett and Thebes. Here's some screens of test where a digit disappears when i move between regions. 
![image](https://user-images.githubusercontent.com/85464983/120946317-e288d100-c6f0-11eb-9fa4-d072d0e6f1aa.png)
![image](https://user-images.githubusercontent.com/85464983/120946372-1a901400-c6f1-11eb-9d2d-1fa7c3f89479.png)
![image](https://user-images.githubusercontent.com/85464983/120946401-31cf0180-c6f1-11eb-9d0d-702f2c425c62.png)

**Comment by Gluegungeek** [comment]
I'm no macro expert. Mostly a noob users. Not exactly sure what screenshots you need. I can wait too tho. Thank you for all your work tho. this program is amazing!

**Comment by KavadATITD** [comment]
Ahhh, sorry about that, I see where I was unclear in hindsight. I'm looking for something like this 
![clock](https://user-images.githubusercontent.com/69826072/120946671-17e1ee80-c6f2-11eb-84b1-d4d4849f2d68.png)

We also have a discord if you find that more convenient than github: https://discord.gg/eKXHJaAZ
I'm also in discord

**Comment by Gluegungeek** [comment]
Ah, here u go:
![image](https://user-images.githubusercontent.com/85464983/120946902-e6b5ee00-c6f2-11eb-999e-52bead96d41b.png)

**Comment by Gluegungeek** [comment]
Err, not sure why that first screen was grayish text: here's a new one:
![image](https://user-images.githubusercontent.com/85464983/120946937-0baa6100-c6f3-11eb-88a5-8e6cf8b6440c.png)

**Comment by KavadATITD** [comment]
Awesome that second one is *exactly* what I needed. Got that 5 fixed. I think there was also some trouble reading 4 and 8 at 648, XXX? If you send shots of those I can fix them uip too.

**Comment by Gluegungeek** [comment]
You ROCK! ty!! here's a 4 and 8. let me know if you need more:
![image](https://user-images.githubusercontent.com/85464983/120947415-62646a80-c6f4-11eb-9ad4-86fe453d206d.png)

**Comment by Gluegungeek** [comment]
![image](https://user-images.githubusercontent.com/85464983/120947506-9dff3480-c6f4-11eb-890c-0644404afad1.png)

**Comment by KavadATITD** [comment]
@Gluegungeek I couldn't find anything wrong with the 4 or 8 in the 648, -157 or 648, -148 shots but the 5 in the 648, -157 was a new variant I added. You may have to go back to exactly 648, -170 to get the bad 4/8

**Comment by Gluegungeek** [comment]
648, -170
![image](https://user-images.githubusercontent.com/85464983/120947745-4d3c0b80-c6f5-11eb-9515-1c39d503e839.png)

**Comment by Gluegungeek** [comment]
maybe region change? here's a Thebes 4 and 8
![image](https://user-images.githubusercontent.com/85464983/120947864-a441e080-c6f5-11eb-9530-bc10807a5424.png)

**Comment by KavadATITD** [comment]
Hmmm Those ones are all working fine for me. I just pushed an update with the new 5s at least. Also make sure your mouse isn't hovering over the clock making it gray when using the gather macro. If you have more trouble, try pulling up test_find_coords and if you find coordinates where it isn't showing the correct values, send clock screenshots for those please.

**Comment by Gluegungeek** [comment]
I just updated and created a new route. It is working perfectly now. Thank you sooo much my man! You are a god among mere mortals!!! lol. seriously tho, I really appreciate it.

**Comment by KavadATITD** [comment]
Lol you are too kind. I'm glad it's working again, thanks for your patience and help, this will benefit everyone using it!
