### ISSUE TITLE
Clay Gathering: not gathering

### ISSUE THREAD

**Issue by Gluegungeek** [DashingStrike/Automato-ATITD10#99]
Hello, me again. The gathering macros are not clicking/gathering clay. Movement works fine, just no clay gathering.
Here's a screenshot of my clay icon. Let me know if I'm doing something wrong. TY kindly.
![image](https://user-images.githubusercontent.com/85464983/121274042-9af07980-c897-11eb-9964-6d84741c48a4.png)

**Comment by KavadATITD** [comment]
Hey @Gluegungeek . Something has your button looking just enough different from standard that it doesn't match what automato is looking for. I'm guessing grass, slate, etc also will not work for you. Make sure that you have your in game UI scale set to the default 125%. If that doesn't work, you may also want to follow the #faq in discord: https://discord.gg/jrf9P7th to make sure windows isn't scaling your UI any.

**Comment by Gluegungeek** [comment]
Ah that was is. My scaling was set to 123% for some reason. As always, thank you! 👍

**Comment by KavadATITD** [comment]
Awesome glad it was an easy fix!
